server:
  port: 9000

spring:
  application:
    name: service-stock

  datasource:
    password: 31415926
    username: root
    url: jdbc:mysql://localhost:3306/db?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          auto-add-partitions: true
          auto-create-topics: true
      bindings:
        fromOrder:
          destination: stock

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

