server:
  port: 9000

spring:
  application:
    name: service-stock

  datasource:
    password: 31415926
    username: root
    url: jdbc:mysql://localhost:3306/miaosha?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
#    数据库连接池配置
    hikari:
      maximum-pool-size: 1000
      connection-timeout: 10000
      minimum-idle: 10

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          auto-add-partitions: true
          auto-create-topics: true
      bindings:
        fromOrder:
          destination: stock
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        enable_lazy_load_no_trans: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

