server:
  port: 9000

spring:
  application:
    name: service-stock

  datasource:
    password: 31415926
    username: root
    url: jdbc:mysql://localhost:3306/db?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

