server:
  port: 9001

spring:
  application:
    name: service-order

  datasource:
    username: root
    password: 31415926
    url: jdbc:mysql://localhost:3306/db?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true

#  rabbitmq:
#    host: localhost
#    port: 5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/