server:
  port: 9001

spring:
  application:
    name: service-order

  datasource:
    username: root
    password: 31415926
    url: jdbc:h2:mem:miaosha;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: h2
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        enable_lazy_load_no_trans: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true
          auto-add-partitions: true
          min-partition-count: 1

      bindings:
        toStock:
          destination: stock
        orderRequest:
          destination: orderAdd


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/